#3.4
quests = ['Naruto', 'Mahito', 'Itachi', 'Enrico Pucci', 'Kira']
print(f"We invite you {quests[0]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[1]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[2]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[3]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[4]} without respect, Yuta Okkotsu")
#надо добавлять в скобках f и "" тогда все работает
print("------------------------------------") #<= заздeляет упражнения
#3.5
quests = ['Naruto', 'Mahito', 'Itachi', 'Enrico Pucci', 'Kira']
qw = quests.pop()
qs = quests.append('Gaara')
print(quests)
print(f"We invite you {quests[0]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[1]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[2]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[3]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[4]} without respect, Yuta Okkotsu")
print(qw)
print("------------------------------------") #<= заздeляет упражнения
#3.6
quests = ['Naruto', 'Mahito', 'Itachi', 'Enrico Pucci', 'Kira']
qw = quests.pop()
qs = quests.append('Gaara')
qn0 = quests.insert(0, 'Sasuke')
qn1 = quests.insert(4, 'L')
qn2 = quests.append('Dio')
print(quests)
print(f"We invite you {quests[0]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[1]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[2]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[3]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[4]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[5]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[6]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[7]} without respect, Yuta Okkotsu")
print("------------------------------------") #<= заздeляет упражнения
#3.7
quests = ['Naruto', 'Mahito', 'Itachi', 'Enrico Pucci', 'Kira']
qw = quests.pop()
qs = quests.append('Gaara')
qn0 = quests.insert(0, 'Sasuke')
qn1 = quests.insert(4, 'L')
qn2 = quests.append('Dio')
print(quests)
print(f"I apologize, {quests[7]}, but the invitation is no longer valid.")
qw7 = quests.pop()
print(f"I apologize, {quests[6]}, but the invitation is no longer valid.")
qw6 = quests.pop()
print(f"I apologize, {quests[5]}, but the invitation is no longer valid.")
qw5 = quests.pop()
print(f"I apologize, {quests[4]}, but the invitation is no longer valid.")
qw4 = quests.pop()
print(f"I apologize, {quests[3]}, but the invitation is no longer valid.")
qw3 = quests.pop()
print(f"I apologize, {quests[2]}, but the invitation is no longer valid.")
qw2 = quests.pop()
print(quests)
del quests[0]
del quests[0]
print(quests)
print("------------------------------------") #<= заздeляет упражнения
#Теперь я хочу полную программу
quests = ['Naruto', 'Mahito', 'Itachi', 'Enrico Pucci', 'Kira']
print(f"We invite you {quests[0]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[1]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[2]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[3]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[4]} without respect, Yuta Okkotsu")
qw = quests.pop()
qs = quests.append('Gaara')
print(quests)
print(f"We invite you {quests[0]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[1]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[2]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[3]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[4]} without respect, Yuta Okkotsu")
print(qw)
qn0 = quests.insert(0, 'Sasuke')
qn1 = quests.insert(4, 'L')
qn2 = quests.append('Dio')
print(quests)
print(f"We invite you {quests[0]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[1]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[2]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[3]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[4]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[5]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[6]} without respect, Yuta Okkotsu")
print(f"We invite you {quests[7]} without respect, Yuta Okkotsu")
print(f"I apologize, {quests[7]}, but the invitation is no longer valid.")
qw7 = quests.pop()
print(f"I apologize, {quests[6]}, but the invitation is no longer valid.")
qw6 = quests.pop()
print(f"I apologize, {quests[5]}, but the invitation is no longer valid.")
qw5 = quests.pop()
print(f"I apologize, {quests[4]}, but the invitation is no longer valid.")
qw4 = quests.pop()
print(f"I apologize, {quests[3]}, but the invitation is no longer valid.")
qw3 = quests.pop()
print(f"I apologize, {quests[2]}, but the invitation is no longer valid.")
qw2 = quests.pop()
print(quests)
del quests[0]
del quests[0]
print(quests)

